name: Actualizar JSON desde Excel

on:
  schedule:
    - cron: '0 * * * *' # Ejecuta cada hora
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # Descargar el archivo Excel
      - name: Descargar Excel desde OneDrive
        run: |
          curl -L "<https://usmcl-my.sharepoint.com/:x:/g/personal/salas_csj_usm_cl/EcLTPK4jWU5PsBzsnlxHH4oB6YHZjmooLtQwzATmr2dupw?e=RyFeZu>" -o data.xlsx

      # Convertir Excel a JSON
      - name: Convertir Excel a JSON
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl
          python -c "
import pandas as pd
data = pd.read_excel('data.xlsx')
data.to_json('data.json', orient='records', indent=2)
"

      # Actualizar JSON en el repositorio
      - name: Subir JSON al repositorio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m 'Actualización automática de JSON desde Excel'
          git push
