---
name: Actualizar JSON desde Excel
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: null
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Descargar Excel desde OneDrive
        run: |
          curl -L "https://usmcl-my.sharepoint.com/:x:/g/personal/salas_csj_usm_cl/EcLTPK4jWU5PsBzsnlxHH4oB6YHZjmooLtQwzATmr2dupw?e=IQMRC7" -o data.xlsx
      - name: Convertir Excel a JSON
        run: >
          python -m pip install --upgrade pip

          pip install pandas openpyxl

          python -c " import pandas as pd data = pd.read_excel('data.xlsx') data.to_json('data.json', orient='records', indent=2) "
      - name: Configurar Git
        run: >
          git config --global user.name "github-actions[bot]"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Subir JSON al repositorio
        run: |
          git add data.json
          git commit -m 'Actualización automática de JSON desde Excel'
          git push
