name: Actualizar JSON desde Excel

on:
  schedule:
    - cron: '0 * * * *' # Ejecuta cada hora
  workflow_dispatch: # Permite ejecuci칩n manual

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # Descargar el archivo Excel
      - name: Descargar Excel desde OneDrive
        run: |
          curl -L "<ENLACE_PUBLICO_EXCEL>" -o data.xlsx

      # Convertir Excel a JSON
      - name: Convertir Excel a JSON
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl
          python -c "
import pandas as pd
data = pd.read_excel('data.xlsx')
data.to_json('data.json', orient='records', indent=2)
"

      # Configuraci칩n de Git para commit
      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Subir JSON al repositorio
      - name: Subir JSON al repositorio
        run: |
          git add data.json
          git commit -m 'Actualizaci칩n autom치tica de JSON desde Excel'
          git push
